### PR TITLE
Use specific example from RentPath

### PR DESCRIPTION
**Pull request by tb0yd**
I tried rewriting my code example to refer to the actual problem we solved at RentPath using the technique I introduce. I'm not sure if it's a better read, though. It's a lot of added technical detail. Thoughts?

### CODE REVIEW

**Comment by tb0yd** [comment]
@martinstreicher ^^

**Comment by michaelstalker** [comment]
@tb0yd I'm interested adding new content to the blog repo 🎉  However, I don't have enough context to evaluate the relative merits of this PR, and your blog post has been published for over two years. I'd like to close this PR. If you feel strongly that I should keep it open, please let me know.

**Comment by doomspork** [comment]
We shouldn't go back and update published articles, we should release new articles for new content as technology changes.

**Comment by tb0yd** [comment]
Hey Michael! 👋 I agree with @doomspork here. The blog post is so old, by now it's quite outdated anyway.

**Pull request closed without merging**
